language: go
sudo: false
go:
  - 1.9.1
install:
  - go get -u github.com/golang/lint/golint
script:
  - make lint
  - go test ./...
after_success:
  - scripts/cover.sh ./...
  - bash <(curl -s https://codecov.io/bash)
